name: DevSecOps Security Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  dependency-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run NPM Audit
        # Fails the build if vulnerabilities of moderate severity or higher are found
        run: npm audit --audit-level=moderate

  sast-codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required to upload SARIF results
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
  zap_scan:
    runs-on: ubuntu-latest
    name: Run ZAP Scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Juice Shop
        run: docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop
        sleep 10 #wait for server to fully start

      - name: ZAP Scan
        run: docker run --network host\ 
              -v $(pwd):/zap/wrk/.rw\
              owasp/zap2docker-stable zap-baseline.py\
              -t http://localhost:3000\
              -r zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html
