name: DevSecOps Security Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  sast-codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required to upload SARIF results
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  dast-zap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Run Juice Shop in background
        run: |
          docker build -t juice-shop .
          docker run -d -p 3000:3000 --name juice-shop juice-shop
          sleep 15 # Give the server time to start

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:3000'
          # Use the official ZAP stable image from GitHub Container Registry
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          # Disable automatic issue creation
          allow_issue_writing: false
          fail_action: false

      - name: Upload ZAP Scan Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-reports
          # The new action version saves reports to the root of the workspace
          path: |
            report_html.html
            report_md.md
            report_sarif.sarif
